### ISSUE TITLE
Datenpunkte Räume werden nicht erstellt.

### ISSUE THREAD

**Issue by exitus27** [o0shojo0o/HeatingControlScript#2]
Alle Heizkörperthermostate sind Räumen zugeordnet und die Funktion Heizung ist angelegt 
Die Fensterkontakte sind als HeatingBraker angelegt und sind Räume und Function angelegt.
Beim Start werden nur die Dantenpunke 0_userdata.0.Heating.heating_period, off_temp und present angelegt, das wars aber auch schon.

Habe zigbee geräteThermostate sind Eurotronic 700153 4er
Fensterkontakte sind von Xiaomi sind alle über zigbee adapter eingebunden.
Ich bekomme unter Heating nicht die Räume als Datenpunkt erstellt.

**Comment by o0shojo0o** [comment]
Deine enum ID ist auch `heating` ? 
![image](https://user-images.githubusercontent.com/19333515/207412322-b16bc4bf-00d7-4030-97bf-e79a1888c75e.png)

**Comment by exitus27** [comment]
![Uploading D30A32E2-9470-4D40-8D53-A45DB672BB43.jpeg…]()

**Comment by exitus27** [comment]
![5BBBA7AD-FAC9-4214-8163-BF4678E2514E](https://user-images.githubusercontent.com/51278719/207442689-9dbc1d18-92e2-4e47-97a1-2dd1b9c4720a.jpeg)

**Comment by exitus27** [comment]
![Uploading A294876B-326F-4287-8193-E0B7CAB2FA05.jpeg…]()

**Comment by o0shojo0o** [comment]
Enterferne mal die Raumsensoren aus der Heizung Enum

**Comment by exitus27** [comment]
Habe ich gemacht hat nicht geklappt 
![D21E79E5-9339-4100-B4F8-A4B6B22780A3](https://user-images.githubusercontent.com/51278719/207462581-b94d7d80-b6be-424e-b740-6e4abb4b7b87.jpeg)
![CF7CBB7B-9FB0-4381-AEE5-EDF31E9F716C](https://user-images.githubusercontent.com/51278719/207462599-7ce89e53-1c43-4157-85ac-3c8c473973d9.jpeg)

**Comment by exitus27** [comment]
jetz geht es ich habe andere datenpunkt von mein Thermostat genommen.
hatte zuerst das zigbee.0.00158d00053d21f0.heating_setpnt_occupied
damit geht es zigbee.0.00158d00053d21f0.heating_setpnt_current
wie kann ich die Temperatur ändern???

**Comment by o0shojo0o** [comment]
> jetz geht es ich habe andere datenpunkt von mein Thermostat genommen.

Ich habe das ganze Thermostat zu den Enum hinzugefügt, das Script sucht sich selbst den richtigen Datenpunkt  

> wie kann ich die Temperatur ändern???

Unter zB. `0_userdata.0.Heating.Wohnzimmer.heating_temperature` für den Tag, `0_userdata.0.Heating.Wohnzimmer.night_reduction` für die Nacht und `0_userdata.0.Heating.off_temp` für die heating_breaker
